Attempt new cleanup strategy

diff --git a/src/@orb.yml b/src/@orb.yml
--- a/src/@orb.yml
+++ b/src/@orb.yml
@@ -52,47 +52,47 @@ commands:
     steps:
     - run:
         command: |
-              # find build files
-              buildFiles=$(find . -name '<< parameters.settings_file >>' | sed 's/.*/&/' | tr '\n' ' ')
-              # get the latest commit which modified the build files
-              lastHash=$(git log -n 1 --pretty=format:%H HEAD -- $buildFiles)
-              # do a check that there actually is more than one revision
-              if ! [ -z "$lastHash" ] && [ $(git rev-list --count HEAD) -gt "1" ]; then
-                # check which previous revision was the last to modify the build files
-                lastPreviousFirstHash=$(git log -n 1 --pretty=format:%H HEAD~1 -- $buildFiles)
-                if [ "$lastPreviousFirstHash" = "$lastHash" ]; then
-                  echo "Build files did not update last commit"
-                else
-                  echo "Build files did update last commit"
-                fi
-                if ! [ -z "$lastPreviousFirstHash" ] && [ $(git rev-list --count $lastPreviousFirstHash) -gt "1" ]; then
-                  lastPreviousSecondHash=$(git log -n 1 --pretty=format:%H $lastPreviousFirstHash~1 -- $buildFiles)
-                  echo "Second last time build files updated at $lastPreviousSecondHash"
-                  if ! [ -z "$lastPreviousSecondHash" ] && [ $(git rev-list --count $lastPreviousSecondHash) -gt "1" ]; then
-                    lastPreviousThirdHash=$(git log -n 1 --pretty=format:%H $lastPreviousSecondHash~1 -- $buildFiles)
-                    if ! [ -z "$lastPreviousThirdHash" ]; then
-                      echo "Third last time build files updated at $lastPreviousThirdHash"
-                    fi
+            # find build files
+            buildFiles=$(find . -name '<< parameters.settings_file >>' | sed 's/.*/&/' | tr '\n' ' ')
+            # get the latest commit which modified the build files
+            lastHash=$(git log -n 1 --pretty=format:%H HEAD -- $buildFiles)
+            # do a check that there actually is more than one revision
+            if ! [ -z "$lastHash" ] && [ $(git rev-list --count HEAD) -gt "1" ]; then
+              # check which previous revision was the last to modify the build files
+              lastPreviousFirstHash=$(git log -n 1 --pretty=format:%H HEAD~1 -- $buildFiles)
+              if [ "$lastPreviousFirstHash" = "$lastHash" ]; then
+                echo "Build files did not update last commit"
+              else
+                echo "Build files did update last commit"
+              fi
+              if ! [ -z "$lastPreviousFirstHash" ] && [ $(git rev-list --count $lastPreviousFirstHash) -gt "1" ]; then
+                lastPreviousSecondHash=$(git log -n 1 --pretty=format:%H $lastPreviousFirstHash~1 -- $buildFiles)
+                echo "Second last time build files updated at $lastPreviousSecondHash"
+                if ! [ -z "$lastPreviousSecondHash" ] && [ $(git rev-list --count $lastPreviousSecondHash) -gt "1" ]; then
+                  lastPreviousThirdHash=$(git log -n 1 --pretty=format:%H $lastPreviousSecondHash~1 -- $buildFiles)
+                  if ! [ -z "$lastPreviousThirdHash" ]; then
+                    echo "Third last time build files updated at $lastPreviousThirdHash"
                   fi
                 fi
-              else
-                echo "Build files did update last commit 2"
               fi
-              if [ -z "$lastPreviousFirstHash" ]; then
-                lastPreviousFirstHash=$lastHash
-              fi
-              if [ -z "$lastPreviousSecondHash" ]; then
-                lastPreviousSecondHash=$lastHash
-              fi
-              if [ -z "$lastPreviousThirdHash" ]; then
-                lastPreviousThirdHash=$lastHash
-              fi
-              echo "$lastPreviousFirstHash" > /tmp/git_last_previous_first_hash
-              echo "$lastPreviousSecondHash" > /tmp/git_last_previous_second_hash
-              echo "$lastPreviousThirdHash" > /tmp/git_last_previous_third_hash
-              echo "$lastHash" > /tmp/git_last_hash
-              echo "success" > /tmp/build_status_success
-              echo "failure" > /tmp/build_status_failure              
+            else
+              echo "Build files did update last commit 2"
+            fi
+            if [ -z "$lastPreviousFirstHash" ]; then
+              lastPreviousFirstHash=$lastHash
+            fi
+            if [ -z "$lastPreviousSecondHash" ]; then
+              lastPreviousSecondHash=$lastHash
+            fi
+            if [ -z "$lastPreviousThirdHash" ]; then
+              lastPreviousThirdHash=$lastHash
+            fi
+            echo "$lastPreviousFirstHash" > /tmp/git_last_previous_first_hash
+            echo "$lastPreviousSecondHash" > /tmp/git_last_previous_second_hash
+            echo "$lastPreviousThirdHash" > /tmp/git_last_previous_third_hash
+            echo "$lastHash" > /tmp/git_last_hash
+            echo "success" > /tmp/build_status_success
+            echo "failure" > /tmp/build_status_failure
         name: Generate Cache Checksum
         working_directory: $CIRCLE_WORKING_DIRECTORY/<< parameters.app_src_directory >>
     - restore_cache:
@@ -118,7 +118,7 @@ commands:
             du -h --max-depth=1 ~/.m2
             if cmp -s "/tmp/git_last_previous_first_hash" "/tmp/git_last_hash" ; then
               echo "No new cache entry will be created"
-            fi          
+            fi 
     - when:
         condition: << parameters.settings_file >>
         steps:
@@ -208,7 +208,7 @@ commands:
             directoriesToBeDeleted=()
             for artifactToBeDeleted in "${artifactsToBeDeleted[@]}"
             do
-              directory=${artifactToBeDeleted%/*} 
+              directory=${artifactToBeDeleted%/*}
               directoriesToBeDeleted+=( $directory )
             done
             # remove duplicates
